baseURL = "/"
languageCode = "en-us"
title = "Quickened Interoperability for 2021"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    subtitle = ""
    subsite = "quintrex"
    ourvision = false
    openGraphSiteName = "Quickened Interoperability, from TRex"
    description = "Shining spotlights on the tracking, profiling of users and the influence of algorithms."
    tagline = "A browser extension to scrape events from Facebook and repost them on the Fediverse"

[permalinks]
    posts = "/posts/:slug/"

[menu]

 [[menu.main]]
    name = "Get in touch"
    url = "/about"
    weight = 20

 [[menu.footer]]
    name = "Something?"
    url ="/about"
    weight = 0

 [[menu.featured]]
    name= "Why Facebook?"
    url = "/why-facebook"
    weight = -180
    pre = "/images/trex-logo.svg"
    post = "Not only the blue exploitative social network should be supported, check out the roadmap"
 [[menu.featured]]
    name = "How this helps Fediverse?"
    url = "/fediverse"
    weight = -170
    pre = "/images/connect with us.svg"
    post = "If you share the values in the Manifesto, you should check it out"
 [[menu.featured]]
    name = "Is this legal? F.A.Q."
    url = "/how-is-this-possible"
    weight = -160
    pre = "/images/reports.svg"
    post = "Yes, because Term of Service is not law. and regardless, this is the right thing to do"
