baseURL = "/"
languageCode = "en-us"
title = "Data liberation, and break the Facebook monopoly!"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    subtitle = ""
    subsite = "quintrex"
    ourvision = false
    openGraphSiteName = "Data liberation, and break the Facebook monopoly!"
    description = "A browser extension to scrape events from Facebook and repost them on the Fediverse"
    tagline = "Technology to liberate events from facebook monopoly"

[permalinks]
    posts = "/posts/:slug/"

[menu]
 [[menu.main]]
    name = "About"
    url = "/about"
    weight = 20
 [[menu.main]]
    name = "Intro slideshow"
    url = "/slides/intro"
    weight = 30

 [[menu.footer]]
    name = "About"
    url ="/about"
    weight = 0

 [[menu.featured]]
    name= "LIBREVENT"
    url = "https://addons.mozilla.org/en-US/firefox/addon/librevent/"
    weight = -180
    pre = "/images/librevent.png"
    post = "Our browser extension meant to set events free from Facebook"
 [[menu.featured]]
    name = "MOBILIZON RESHARE"
    url = "/mobilizon-reshare/"
    weight = -170
    pre = "/images/mobilizon.png"
    post = "A tool to broadcast Mobilizon events on social media platforms"
 [[menu.featured]]
    name = "MOBILIZE.BERLIN"
    url = "https://mobilize.berlin/"
    weight = -160
    pre = "/images/park.jpg"
    post = "Check out a use case. Your can be the next!"
