baseURL = "/"
languageCode = "en-us"
title = "Quickened Interoperability for 2021"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    subtitle = ""
    subsite = "quintrex"
    ourvision = false
    openGraphSiteName = "Quickened Interoperability, from TRex"
    description = "Shining spotlights on the tracking, profiling of users and the influence of algorithms."
    tagline = "A browser extension to scrape events from Facebook and repost them on the Fediverse"

[permalinks]
    posts = "/posts/:slug/"

[menu]

 [[menu.main]]
    name = "Get in touch"
    url = "/about"
    weight = 20

 [[menu.footer]]
    name = "Get in touch"
    url ="/about"
    weight = 0

 [[menu.featured]]
    name= "LIBREVENT"
    url = "https://addons.mozilla.org/en-US/firefox/addon/librevent/"
    weight = -180
    pre = "/images/librevent.png"
    post = "Our browser extension meant to set events free from Facebook"
 [[menu.featured]]
    name = "MOBILIZON"
    url = "https://joinmobilizon.org/en/"
    weight = -170
    pre = "/images/mobilizon.png"
    post = "If you share the values in the Manifesto, you should check it out"
 [[menu.featured]]
    name = "MOBILIZE.BERLIN"
    url = "https://mobilize.berlin/"
    weight = -160
    pre = "/images/park.jpg"
    post = "Our first use case. Coming on strong :)"
